version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql/data

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/food-pictures
    ports:
      - "3000:3000"
    links:
      - db
  
  

 


