
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  
  
development:
  <<: *default
  database: food-pictures_development

# 開発環境とテスト環境とで変更
test:
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  database: food-pictures_test


production:
  <<: *default
  database: food-pictures_production
  username: food-pictures
  password: <%= ENV['FOOD-PICTURES_DATABASE_PASSWORD'] %>
